### PR TITLE
Fix copy pasta in Board.prototype.analogRead. Fixes #12

### LINKED ISSUE #12: Copy pasta in Board.prototype.analogRead
```
/Users/rick/clonez/duino/lib/board.js:191
    this.log('info', 'analogRead to pin ' + pin + ': ' + val.green);
                                                      ^
ReferenceError: val is not defined
```

### PR DESCRIPTION
**Pull request by rwaldron**
Signed-off-by: Rick Waldron waldron.rick@gmail.com waldron.rick@gmail.com

### CODE REVIEW

**Comment by ecto** [comment]
don't frettuccini

**Comment by ecto** [comment]
okay that was kind of a reach for a joke haha. thanks man

**Comment by rwaldron** [comment]
hahah was a good one ;)

**Comment by rwaldron** [comment]
I think you closed this without actually merging it. I just rebased and the change is missing (it's also not present in commit log)

**Comment by ecto** [comment]
wrong button >_>

**Comment by ecto** [comment]
pushed to npm as 0.0.5 with your branch merged

**Pull request merged**
